# .github/workflows/ci.yml
name: Node.js CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup test environment
        run: |
          # Mock NotificationService globally
          echo "global.NotificationService = class { notify() { return true } };" > test/setup-mock.js

      - name: Run ESLint
        run: npm run lint --if-present

      - name: Run tests
        env:
          MONGO_URI: mongodb://localhost:27017/testdb
          NODE_ENV: test
        run: mocha --require test/setup-mock.js test/*.js

      - name: Build app
        run: npm run build --if-present

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Production (placeholder)
        run: echo "Add deployment script here (AWS, Heroku, Vercel, etc.)"
